[book]
authors = ["JL710"]
language = "en"
src = "src"
title = "Unofficial Iced Guide"

[build]
create-missing = false

[output.html.playground]
runnable = false

[output.html]
git-repository-url = "https://github.com/JL710/iced-guide"
edit-url-template = "https://github.com/JL710/iced-guide/blob/main/{path}"

[output.html.fold]
enable = true
level = 0

[preprocessor.project-path]
command = "mdbook-project-path"
before = ["links"]
paths = [["code", "../iced-guide-examples"]]
