[package]
name = "app_structure_example"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", version = "0.13.0-dev", features = [
    "tokio",
] }
reqwest = { version = "0.12.5", features = ["json"] }
serde_json = "1.0.120"
